### ISSUE TITLE
`make test` fails with error using python 3.10

### ISSUE THREAD

**Issue by jasonmclaren** [chendaniely/pyprojroot#47]
See below for the error. I think this is a problem with pytest 6.1.1 -- fixed in pytest 6.2.5. (See https://stackoverflow.com/questions/69528842/an-error-while-trying-to-execute-tests-on-python-3-10-with-pytest)

$ make test
PYTHONPATH=src python -m pytest
===================================== test session starts =====================================
platform darwin -- Python 3.10.6, pytest-6.1.2, py-1.11.0, pluggy-0.13.1
rootdir: /Users/jason/src/pyprojroot
collected 0 items / 1 error

=========================================== ERRORS ============================================
_____________________________ ERROR collecting tests/test_here.py _____________________________
../../.pyenv/versions/3.10.6/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:162: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:359: in _rewrite_test
    co = compile(tree, fn_, "exec", dont_inherit=True)
E   TypeError: required field "lineno" missing from alias
=================================== short test summary info ===================================
ERROR tests/test_here.py - TypeError: required field "lineno" missing from alias
!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================== 1 error in 0.21s =======================================
make: *** [test] Error 2

**Comment by yashikakhurana** [comment]
@jasonmclaren it solved if we use python3 instead of python in commands, I am submitting a patch for that

**Comment by yashikakhurana** [comment]
@jasonmclaren fixed in here- https://github.com/chendaniely/pyprojroot/pull/49

**Comment by jasonmclaren** [comment]
@yashikakhurana It looks like you found another related problem, but this still doesn't work for me using python3 (which points to 3.11 with my current pyenv configuration).

The problem is an incompatibility between pytest 6.1 and python 3.11. I confirmed (using tox) that it works for python 3.7, 3.8, 3.9, 3.10.

I'm currently testing other versions of pytest with all the relevant python versions.

@chendaniely could you please re-open this issue for the time being?

**Comment by jasonmclaren** [comment]
Fixed in [PR 54](https://github.com/chendaniely/pyprojroot/pull/54).

**Comment by jasonmclaren** [comment]
Thanks for merging that fix!

**Comment by yashikakhurana** [comment]
@jasonmclaren thank you :)
